first week
svetafilimonova/loftschool_web_beginners pull request #1
Opened 2017-07-31 19:13 UTC by svetafilimonova

Маргарита, посмотри пожалуйста

2017-07-31 20:05 UTC, pitasam requested changes
http://joxi.ru/DmB03zvtN6MoaA видишь у тебя блок с текстом съехал. Это из-за того, что ты задала марджин сверху заголовку http://joxi.ru/v29n5XVtGjobwA. Это особенность такая в верстке. Поэтому отступы лучше задавать внутри блока паддингами.
http://joxi.ru/8An9gpjFqKPe12 нет фиксированной ширины. Как браузер этот блок по центру поставит, если блок по умолчанию тянется на весь экран.
http://joxi.ru/bmo9M0jFMlPgJA хитро) Но это не картинка. Эту точку можно нарисовать с помощью css. Тут нужно ссылке(<a>) задать ширину и высоту(не такую узкую, а чтобы и ободок тоже помещался). А кружок нарисовать псевдоэлементом. Ободок правильно через псевдоэлемент сделала.
http://joxi.ru/J2baODjI4MK7Km высота и ширина кнопке задается через паддинги внутри кнопки. Не нужно будет мучиться с горизонтальным и вертикальным выравниванием текста.
http://joxi.ru/L21dDXVH6DbM9m это ты пыталась сасс использовать?

2017-07-31 20:05 UTC, pitasam commented on index.html
> +                <div class="container">
Тут контейнер уже не нужен

2017-07-31 20:05 UTC, pitasam commented on index.html
> +                <main class="greeting__content">
В теге main должна находиться изменяемая часть страницы. Но так же Саша рассказывал, почему можно сделать wrapper тегом main. А тут он никак не подходит.

2017-07-31 20:05 UTC, pitasam commented on index.html
> +            <div class="greeting__container">
Контейнер здесь не нужен. Есть общий же.

2017-07-31 20:05 UTC, pitasam commented on index.html
> +                        <div class="section__title section__title_white"> натуральные бургеры</div>
Почему такой же класс как и у "Мы делаем"? Эти две надписи отличаются. Даже шрифт разный у них.

2017-07-31 20:05 UTC, pitasam commented on index.html
> +            <div class="about__description">
Одинаковые элементы верстаем списком.

2017-07-31 20:05 UTC, pitasam commented on index.html
> +                    <div class="about__description-title">100% свежее мясо</div>
Посмотри на этот текст и на текст в первой секции "натуральные бургеры".

2017-08-01 12:22 UTC, svetafilimonova commented
Маргарита, посмотри пожалуйста, я все поправила

2017-08-02 11:51 UTC, svetafilimonova commented
Маргарита, я добавила flexbox и svg-иконки

2017-08-06 09:01 UTC, merged